### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by JobLeonard** [linnarsson-lab/loom-viewer#75]
I figured it might be nice to have a "general" issue that tracks what I am focusing on now, since all of these separate issues would make it trickier to follow which one is being prioritised. I'll comment here as things progress, so it's easier to track where I am (for both of us, really)

So as noted in #71 I was focusing on the following tasks right now, in order:

1. minor clean-up of bugs
2. redesign UI
3. "paste genes" UI element
4. lasso select

However, with #73 it becomes obvious that point 2 will be quite a large effort, so I'll shuffle this around: first clean-up, paste genes element, then UI migration, then lasso select.

So my current task list looks like this:

- [x] minor clean-up of bugs + small improvements that are directly useful and/or relevant for later coding structure
  - [x] filter by gene value functionality
  - [x] sort by gene functionality
  - [x] view state unification (almost done)
  - [x] filter and sort settings as part of view state
- [x] "paste genes" UI element
- [ ] UI migration - see #38, #73 
- [ ] Lasso Select - see #74
