### ISSUE TITLE
Loom 1.0

### ISSUE THREAD

**Issue by JobLeonard** [linnarsson-lab/loom-viewer#98]
Transcription of my notes on what needs to be fixed before Loom 1.0 is ready for the public. Only includes things that I have not already addressed (already fixed: optimising the search of dataset list, pasting genes interface, sorting of attribute keys, a number of heatmap/scatterplot/sparkline bugs).

### Client

- [x] General:
  - [x] split Loompy, loom cli and loom server/browser into separate packages.
  - [x] Add filtering component to all views that shows which values are filtered out for which attribute (currently only visible in the Legend when an attribute is selected for coloring)
  - [x] Scrollbar bugs in Safari

- Sparkline
  - ~~zoom option~~ for post-release

- [x] Scatterplot
  - [x] more logical view settings
    - [x] quick settings (tSNE, PCS, SFDP, Log)  as descriptive links, not buttons
    - [x] attribute selection for x/y/colors
  -  ~~axes~~ post-1.0 release (scatterplots are mainly used for tSNE plots anyway)
  - [x] labels
  - [x] heatmap scale

- [ ] Introduction page
  - [ ] tutorials to explain usage and power user features
    - [ ] quick links
    - [ ] illustrative animated gifs 

After all of the above has been implemented:
- [ ] Verify the website works in every (modern) browser on major desktop platforms
  - [x] Chrome (Mac, Linux, Windows)
  - [x] Firefox (Mac, Linux, Windows)
  - [ ] Safari (Mac)
  - [ ] Edge (Windows

Optional:
- selection of values (instead of filtering them out). Requires thinking about how to do so intuitively
- bookmarks view (more elaborate version of "share link"
- [x] fix dataset list "empty element" bug when clicking the navbar multiple time (visual bug, does not break anything)
- [x] fix Navbar visual bugs
- Scatterplot: implement edges (requires deep level retooling of Canvas component, perhaps better to merge with jump to interactive sketches instead of static plots)

### Server
- [x] Heatmap Sorting

**Comment by JobLeonard** [comment]
New priority list, as per lab meeting and meeting with Sten today:

- [ ] Make it easier to get started
  - [ ] Safari dataset-list bug (see #121)
  - [ ] windows installation without compilation (see #139)
  - [ ] when creating a new loom-datasets folder, it should also create two demo projects:
    - [ ] `/test/test.loom`
    - [ ] `/Linnarsson Lab/cortex.loom` (requires #132 to be closed)
  - [ ] expansion page (see #114)
  - [ ] documentation: installation instructions (see #81)
    - [ ] (high priority)
- [ ] authentication support for private loom servers (see #32)
- [ ] auto-update when cache is out of sync with loom file (see #77)
  - [ ] server: keep track if expansion has happened AFTER loom file modification
  - [ ] client: empty cache when server says loom file has been modified, warn about expansion
- [ ] grouped sparkline bug (see #61, #122)

Other enhancements:
- [ ] documentation: tutorials (see #107)
- [ ] export selected genes to CSV or JSON (see #138)
- [ ] "save as A4/US Letter-sized PNG"(see #57)
- [ ] on-scatterplot labels (see #102)
- [ ] support for multiple layers
- [ ] improve memory footprint (see #97)
